# Generated by Django 4.2.5 on 2023-09-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Optional subtitle for the page', max_length=255, null=True),
        ),
    ]
