# Generated by Django 4.2.5 on 2023-09-22 19:46

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock(features=['h2', 'bold', 'italic'], help_text='Основной контент', label='Текст')), ('image', wagtail.blocks.StructBlock([('caption', wagtail.blocks.CharBlock()), ('img', wagtail.images.blocks.ImageChooserBlock())], label='Картинка с подписью')), ('quotes', wagtail.blocks.RichTextBlock()), ('list', wagtail.blocks.RichTextBlock())], default={}, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Надпись с призывом к действию', max_length=70, null=True),
        ),
    ]
