# Generated by Django 4.2.5 on 2023-09-23 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contactinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
