# Generated by Django 4.2.5 on 2023-09-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_contactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='main_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Основной номер телефона'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='second_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Дополнительный номер телефона'),
        ),
    ]
