# Generated by Django 4.2.5 on 2023-09-23 14:05

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('home', '0010_alter_contactinfo_main_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, help_text='Надпись с призывом к действию', max_length=70, null=True)),
                ('content', wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock(features=['h2', 'bold', 'italic'], help_text='Основной контент', label='Текст')), ('image', wagtail.blocks.StructBlock([('caption', wagtail.blocks.CharBlock()), ('img', wagtail.images.blocks.ImageChooserBlock())], label='Картинка с подписью')), ('quotes', wagtail.blocks.RichTextBlock()), ('list', wagtail.blocks.RichTextBlock())], default={}, use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_college',
            field=wagtail.fields.RichTextField(blank=True, help_text='Текст о коллегии', null=True),
        ),
    ]
