# Generated by Django 4.2.5 on 2023-09-25 03:23

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_servicespage_remove_homepage_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespage',
            name='subtitle_second',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Подзаголовок к призыву'),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='content',
            field=wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock(features=['h2', 'bold', 'italic'], help_text='Основной контент', label='Текст')), ('image', wagtail.blocks.StructBlock([('caption', wagtail.blocks.CharBlock(label='Подпись')), ('img', wagtail.images.blocks.ImageChooserBlock(label='Картинка'))], label='Картинка с подписью')), ('quotes', wagtail.blocks.RichTextBlock(label='Цитата')), ('list', wagtail.blocks.StreamBlock([('bullet', wagtail.blocks.StructBlock([('header', wagtail.blocks.CharBlock(label='Заголовок пункта')), ('text', wagtail.blocks.RichTextBlock(label='Текст пункта'))], label='Пункт'))], label='Список с пунктами'))], default={}, use_json_field=True, verbose_name='Контент страницы'),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Заголовок к призыву'),
        ),
    ]
