# Generated by Django 4.2.5 on 2023-10-05 12:45

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('home', '0016_testpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('role', models.CharField(max_length=70, verbose_name='Должность')),
                ('short_description', wagtail.fields.RichTextField(blank=True, help_text='Текст в карточках', null=True)),
                ('content', wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock(features=['h2', 'bold', 'italic'], help_text='Основной контент', label='Текст'))], default={}, use_json_field=True, verbose_name='Контент страницы')),
                ('tags', models.ManyToManyField(blank=True, to='home.servicescategory')),
            ],
            options={
                'verbose_name': 'Адвокат',
                'verbose_name_plural': 'Адвокаты',
            },
            bases=('wagtailcore.page',),
        ),
    ]
