# Generated by Django 4.2.5 on 2023-10-05 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('home', '0017_lawyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyers',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Адвокаты',
                'verbose_name_plural': 'Адвокатыг',
            },
            bases=('wagtailcore.page',),
        ),
    ]
