# Generated by Django 4.2.5 on 2023-10-08 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_lawyers'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerServicesCategoryRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.lawyer')),
                ('services_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.servicescategory')),
            ],
            options={
                'unique_together': {('lawyer', 'services_category')},
            },
        ),
    ]
