# Generated by Django 4.2.5 on 2023-10-08 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_lawyerservicescategoryrelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerservicescategoryrelationship',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer', to='home.lawyer'),
        ),
        migrations.AlterField(
            model_name='lawyerservicescategoryrelationship',
            name='services_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_category', to='home.servicescategory'),
        ),
    ]
