# Generated by Django 4.2.5 on 2023-10-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_delete_lawyerservicescategoryrelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='education',
            field=models.CharField(default='Нету', max_length=70, verbose_name='Образование'),
            preserve_default=False,
        ),
    ]
