# Generated by Django 4.2.5 on 2023-10-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_lawyer_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer',
            name='education',
        ),
        migrations.AddField(
            model_name='lawyer',
            name='experience',
            field=models.CharField(default='Более 15 лет', max_length=70, verbose_name='Опыт работы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lawyer',
            name='reg_num',
            field=models.CharField(default='\x16', max_length=70, verbose_name='Регистрационный номер'),
            preserve_default=False,
        ),
    ]
