# Generated by Django 4.2.5 on 2023-10-09 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_servicespage_header_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicespage',
            name='header_title',
        ),
    ]
